import type { Metadata } from 'next';
import '../globals.css';
import { oswald } from '../font';
import Providers from '../store/provider';
import { Layout } from '@/components';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={oswald.className}>
        <Layout>
          <Providers>{children}</Providers>
        </Layout>
      </body>
    </html>
  );
}
