import type { Metadata } from 'next';
import { Goldman, Oswald } from 'next/font/google';
import './globals.css';
import Providers from '../store/provider';
import { oswald } from '../font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={oswald.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
