import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import './globals.css';
import Providers from './store/provider';

const inter = Oswald({ weight: '400', subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
